version: "3.9"
services:
  db:
    image: postgres:16
    container_name: mcpsql_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./datasets:/datasets              # where we keep dumps/scripts
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 20

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: mcpsql_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin:/var/lib/pgadmin

# Optional: one-shot init job to load Pagila when DB is healthy
  load_pagila:
    image: postgres:16
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./datasets:/datasets
    entrypoint: ["bash", "-lc"]
    command: >
      "psql -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /datasets/pagila-schema.sql && \
       psql -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB} -f /datasets/pagila-data.sql"
    environment:
      PGPASSWORD: ${POSTGRES_PASSWORD}

volumes:
  pgdata:
  pgadmin:
