[project]
name = "mcp-server"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.2.0",
    "psycopg[binary]>=3.1",
    "sqlparse>=0.5",
    "requests>=2.32"
]

[tool.uv]
# no special settings needed